apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: <your-docker-username>/bankapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
 
